# Generated by Django 4.0.5 on 2022-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tag_alter_course_options_course_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='lesson',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.hashtag'),
        ),
    ]
